pipeline {
    agent any
    
    tools {
        maven 'Maven-3.9'
        jdk 'JDK-17'
    }
    
    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out source code'
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                echo 'Building application'
                dir('user-read-single-record') {
                    sh 'mvn clean compile'
                }
            }
        }
        
        stage('Test') {
            steps {
                echo 'Running tests'
                dir('user-read-single-record') {
                    sh 'mvn test'
                }
            }
        }
        
        stage('Package') {
            steps {
                echo 'Packaging application'
                dir('user-read-single-record') {
                    sh 'mvn package -DskipTests'
                }
            }
        }
        
        stage('Docker Build') {
            steps {
                dir('user-read-single-record') {
                    sh 'docker build -t user-read-single-record:${BUILD_NUMBER} .'
                    sh 'docker tag user-read-single-record:${BUILD_NUMBER} user-read-single-record:latest'
                }
            }
        }
        
        stage('Deploy') {
            steps {
                dir('user-read-single-record') {
                    sh 'docker-compose down || true'
                    sh 'docker-compose up -d'
                }
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
    }
}