pipeline {
    agent any
    
    tools {
        maven 'Maven-3.9'
        jdk 'JDK-17'
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                dir('User-Api-GW') {
                    sh 'mvn clean compile'
                }
            }
        }
        
        stage('Test') {
            steps {
                dir('User-Api-GW') {
                    sh 'mvn test'
                }
            }
        }
        
        stage('Package') {
            steps {
                dir('User-Api-GW') {
                    sh 'mvn package -DskipTests'
                }
            }
        }
        
        stage('Docker Build') {
            when {
                expression { 
                    return sh(script: 'which docker', returnStatus: true) == 0
                }
            }
            steps {
                dir('User-Api-GW') {
                    sh 'docker build -t user-api-gw:${BUILD_NUMBER} .'
                    sh 'docker tag user-api-gw:${BUILD_NUMBER} user-api-gw:latest'
                }
            }
        }
        
        stage('Deploy') {
            when {
                expression { 
                    return sh(script: 'which docker-compose', returnStatus: true) == 0
                }
            }
            steps {
                dir('User-Api-GW') {
                    sh 'docker-compose down || true'
                    sh 'docker-compose up -d'
                }
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
    }
}