pipeline {
    agent any
    
    tools {
        maven 'Maven-3.9'
        jdk 'JDK-17'
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                dir('User-Api-GW') {
                    sh 'mvn clean compile'
                }
            }
        }
        
        stage('Test') {
            steps {
                dir('User-Api-GW') {
                    sh 'mvn test'
                }
            }
        }
        
        stage('Package') {
            steps {
                dir('User-Api-GW') {
                    sh 'mvn package -DskipTests'
                }
            }
        }
        
        stage('Docker Build') {
            steps {
                dir('User-Api-GW') {
                    script {
                        if (sh(script: 'which docker', returnStatus: true) == 0) {
                            sh 'docker build -t user-api-gw:${BUILD_NUMBER} .'
                            sh 'docker tag user-api-gw:${BUILD_NUMBER} user-api-gw:latest'
                        } else {
                            echo 'Docker not available, skipping Docker build'
                        }
                    }
                }
            }
        }
        
        stage('Deploy') {
            steps {
                dir('User-Api-GW') {
                    script {
                        if (sh(script: 'which docker-compose', returnStatus: true) == 0) {
                            sh 'docker-compose down || true'
                            sh 'docker-compose up -d'
                        } else {
                            echo 'Docker Compose not available, skipping deployment'
                        }
                    }
                }
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
    }
}